#!/bin/bash

# Step 1: Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
    sudo apt update
    sudo apt install nginx -y


# Step 2: Check if Nginx is already listening on port 80
if ! sudo lsof -i :80 | grep LISTEN &> /dev/null; then
    # Step 3: Configure Nginx to listen on port 80
    sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/nginx.conf

    # Step 4: Restart Nginx service
    sudo systemctl restart nginx

